(() => {
 const labels={action:'행동',expression:'표정',feature:'외형',attire:'의상',setting:'배경',object:'소품',style:'그림체',count:'인원',artist:'작가',character:'캐릭터',series:'작품',meta:'메타',meme:'밈',other:'기타'};
 const selector='[data-tag-input],[data-field="appearance"],#storySeed,#storyPlace,#storyAction,#storyState,[data-field="personality"],#storyDirection,#currentDirection,#currentPlace,#personalityInput,#system_prompt,#author_note,#before_task,#after_task,#task_template,#aiGoal';
 const box=document.createElement('div');box.id='tagSuggestions';box.className='tag-suggestions';box.hidden=true;box.setAttribute('role','listbox');box.setAttribute('aria-label','태그 자동완성');document.body.append(box);

 const help=document.createElement('div');help.id='tagExplanation';help.hidden=true;help.setAttribute('role','status');help.style.cssText='position:fixed;margin:0;inset:auto;box-sizing:border-box;max-width:330px;padding:12px 15px;background:#fff9e9;color:#283e32;border:1px solid #d8cda9;border-radius:10px;box-shadow:0 5px 20px #24342b24;font:13px/1.6 sans-serif;overflow-wrap:anywhere;z-index:1200';document.body.append(help);
 for(const node of [box,help]){node.setAttribute('popover','manual');node.style.margin='0';node.style.inset='auto'}
 const normal=s=>s.toLowerCase().replace(/_/g,' ').replace(/\s+/g,' ').trim();
 function show(node,el){const parent=el.closest('dialog[open]')||document.body;if(node.parentElement!==parent)parent.append(node);node.hidden=false;if(!node.matches(':popover-open'))node.showPopover()}
 function hideHelp(){helpVersion++;if(help.matches(':popover-open'))help.hidePopover();help.hidden=true}
 async function lookup(q,signal){if(!q||q.length>80)return [];const r=await fetch('/api/tags?q='+encodeURIComponent(q),{signal});return r.ok?(await r.json()).items:[]}
 async function explain(e){const el=e.target,p=part(el);if(!p)return;hide();hideHelp();const current=helpVersion;let query=el.value.slice(p.start,p.end).trim();if(!query)return;try{
  let rows=await lookup(query),row=rows.find(r=>normal(r.tag)===normal(query)||normal(r.translation||'')===normal(query));
  if(!row){let a=p.pos,b=p.pos;while(a>p.start&&!/\s/.test(el.value[a-1]))a--;while(b<p.end&&!/\s/.test(el.value[b]))b++;query=el.value.slice(a,b).replace(/^[.!?;:"']+|[.!?;:"']+$/g,'');rows=await lookup(query);row=rows.find(r=>normal(r.tag)===normal(query)||normal(r.translation||'')===normal(query))}
  if(current!==helpVersion||document.activeElement!==el)return;if(!row){suggest();return}
  help.replaceChildren();const title=document.createElement('strong');title.textContent=row.tag;const meaning=document.createElement('div');meaning.textContent=row.translation||'한국어 뜻이 등록되지 않은 태그입니다.';const category=document.createElement('div');category.textContent=row.categories.map(c=>labels[c]||c).join(' · ');category.style.cssText='font-size:11px;color:#727969;margin-top:5px';help.append(title,meaning,category);show(help,el);const r=help.getBoundingClientRect();help.style.left=Math.max(8,Math.min(e.clientX+10,innerWidth-r.width-8))+'px';help.style.top=Math.max(8,Math.min(e.clientY+12,innerHeight-r.height-8))+'px';
 }catch{if(current===helpVersion)hideHelp()}}

 let helpVersion=0;
 let input=null,items=[],selected=-1,version=0,timer=null,controller=null,segment=null;
 function hide(){if(box.matches(':popover-open'))box.hidePopover();box.hidden=true;version++;clearTimeout(timer);controller?.abort();if(input){input.setAttribute('aria-expanded','false');input.removeAttribute('aria-activedescendant')}}
 function part(el){const pos=el.selectionStart;if(pos!==el.selectionEnd)return null;const text=el.value;let start=pos,end=pos;while(start>0&&!/[\n,]/.test(text[start-1]))start--;while(end<text.length&&!/[\n,]/.test(text[end]))end++;while(start<pos&&/\s/.test(text[start]))start++;const raw=text.slice(start,end),weight=raw.match(/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)::\s*/);if(weight)start+=weight[0].length;if(text.slice(start,end).trimEnd().endsWith('::'))end=text.slice(0,end).trimEnd().length-2;return {start,end,query:text.slice(start,Math.min(pos,end)).trim(),value:text,pos}}
 function position(){if(!input)return;const r=input.getBoundingClientRect();box.style.left=Math.max(8,Math.min(r.left,innerWidth-328))+'px';box.style.width=Math.min(Math.max(r.width,280),innerWidth-16)+'px';const below=innerHeight-r.bottom;box.style.top=(below<180?Math.max(8,r.top-Math.min(260,r.top-8)):r.bottom+4)+'px';box.style.maxHeight=Math.max(90,Math.min(260,below<180?r.top-16:below-12))+'px'}
 function mark(){[...box.children].forEach((row,i)=>{row.setAttribute('aria-selected',i===selected?'true':'false');if(i===selected){input.setAttribute('aria-activedescendant',row.id);row.scrollIntoView({block:'nearest'})}})}
 function choose(index){const row=items[index];if(!row||!segment||input.value!==segment.value)return hide();const suffix=input.value.slice(segment.end),replacement=row.tag+(suffix?'':', ');input.setRangeText(replacement,segment.start,segment.end,'end');hide();input.dispatchEvent(new Event('input',{bubbles:true}));input.focus();hide()}
 async function suggest(){hide();hideHelp();const el=input;if(!el||el.disabled||el.readOnly)return;const p=part(el);if(!p||!p.query)return;const current=version;timer=setTimeout(async()=>{controller=new AbortController();try{let result={items:p.query.length<=80?await lookup(p.query,controller.signal):[]};if(!result.items.length){const word=p.query.match(/[^\s]+$/);if(word&&word[0]!==p.query){p.start=p.pos-word[0].length;p.query=word[0];p.end=p.pos;while(p.end<el.value.length&&!/[\s,\n]/.test(el.value[p.end]))p.end++;result={items:await lookup(p.query,controller.signal)}}}if(current!==version||document.activeElement!==el)return;items=result.items;segment=p;selected=-1;box.replaceChildren();for(const [i,item] of items.entries()){const row=document.createElement('div');row.id='tagOption'+i;row.setAttribute('role','option');row.setAttribute('aria-selected','false');const name=document.createElement('span');name.textContent=item.tag;if(item.translation){const ko=document.createElement('span');ko.textContent=item.translation;ko.style.cssText='display:block;font-size:12px;color:#516457;margin-top:3px;white-space:normal';name.append(ko)}const category=document.createElement('small');category.textContent=item.categories.map(c=>labels[c]||c).join(' · ');row.append(name,category);row.addEventListener('pointerdown',e=>{e.preventDefault();choose(i)});box.append(row)}box.hidden=!items.length;if(items.length)show(box,el);el.setAttribute('aria-expanded',String(!!items.length));position()}catch(e){if(e.name!=='AbortError'&&current===version)hide()}},120)}
 document.addEventListener('focusin',e=>{if(!e.target.matches(selector))return;hide();input=e.target;input.setAttribute('aria-autocomplete','list');input.setAttribute('aria-controls',box.id);input.setAttribute('autocomplete','off');suggest()});
 document.addEventListener('input',e=>{if(e.target===input&&!e.isComposing)suggest()});
 document.addEventListener('compositionend',e=>{if(e.target===input)suggest()});
 document.addEventListener('click',e=>{if(e.target===input)explain(e)});
 document.addEventListener('focusout',e=>{if(e.target===input){hide();hideHelp()}});
 document.addEventListener('pointerdown',e=>{if(e.target!==input&&!box.contains(e.target)){hide();hideHelp()}});
 document.addEventListener('keydown',e=>{if(e.target!==input||e.isComposing)return;if(e.key==='Escape')hideHelp();if(box.hidden)return;if(e.key==='Escape'){e.preventDefault();hide()}else if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();selected=(selected+(e.key==='ArrowDown'?1:items.length-1)+items.length)%items.length;mark()}else if((e.key==='Enter'||e.key==='Tab')&&selected>=0){e.preventDefault();choose(selected)}});
 const dismiss=()=>{hide();hideHelp()};addEventListener('resize',dismiss);addEventListener('scroll',e=>{if(!box.contains(e.target))dismiss()},true);document.addEventListener('close',dismiss,true);
})();
