(() => {
 const labels={action:'행동',expression:'표정',feature:'외형',attire:'의상',setting:'배경',object:'소품',style:'그림체',count:'인원',artist:'작가',character:'캐릭터',series:'작품',meta:'메타',meme:'밈',other:'기타'};
 const selector='[data-tag-input],[data-field="appearance"],#storySeed,#storyPlace,#storyAction,#storyState';
 const box=document.createElement('div');box.id='tagSuggestions';box.className='tag-suggestions';box.hidden=true;box.setAttribute('role','listbox');box.setAttribute('aria-label','태그 자동완성');document.body.append(box);
 let input=null,items=[],selected=-1,version=0,timer=null,controller=null,segment=null;
 function hide(){box.hidden=true;version++;clearTimeout(timer);controller?.abort();if(input){input.setAttribute('aria-expanded','false');input.removeAttribute('aria-activedescendant')}}
 function part(el){const pos=el.selectionStart;if(pos!==el.selectionEnd)return null;const text=el.value;let start=pos,end=pos;while(start>0&&!/[\n,]/.test(text[start-1]))start--;while(end<text.length&&!/[\n,]/.test(text[end]))end++;while(start<pos&&/\s/.test(text[start]))start++;return {start,end,query:text.slice(start,pos).trim(),value:text,pos}}
 function position(){if(!input)return;const r=input.getBoundingClientRect();box.style.left=Math.max(8,Math.min(r.left,innerWidth-328))+'px';box.style.width=Math.min(Math.max(r.width,280),innerWidth-16)+'px';const below=innerHeight-r.bottom;box.style.top=(below<180?Math.max(8,r.top-Math.min(260,r.top-8)):r.bottom+4)+'px';box.style.maxHeight=Math.max(90,Math.min(260,below<180?r.top-16:below-12))+'px'}
 function mark(){[...box.children].forEach((row,i)=>{row.setAttribute('aria-selected',i===selected?'true':'false');if(i===selected){input.setAttribute('aria-activedescendant',row.id);row.scrollIntoView({block:'nearest'})}})}
 function choose(index){const row=items[index];if(!row||!segment||input.value!==segment.value)return hide();const suffix=input.value.slice(segment.end),replacement=row.tag+(suffix?'':', ');input.setRangeText(replacement,segment.start,segment.end,'end');hide();input.dispatchEvent(new Event('input',{bubbles:true}));input.focus();hide()}
 async function suggest(){hide();const el=input;if(!el||el.disabled)return;const p=part(el);if(!p||!p.query||p.query.length>80)return;const current=version;timer=setTimeout(async()=>{controller=new AbortController();try{const response=await fetch('/api/tags?q='+encodeURIComponent(p.query),{signal:controller.signal});if(!response.ok)throw Error();const result=await response.json();if(current!==version||document.activeElement!==el)return;items=result.items;segment=p;selected=-1;box.replaceChildren();for(const [i,item] of items.entries()){const row=document.createElement('div');row.id='tagOption'+i;row.setAttribute('role','option');row.setAttribute('aria-selected','false');const name=document.createElement('span');name.textContent=item.tag;const category=document.createElement('small');category.textContent=item.categories.map(c=>labels[c]||c).join(' · ');row.append(name,category);row.addEventListener('pointerdown',e=>{e.preventDefault();choose(i)});box.append(row)}box.hidden=!items.length;el.setAttribute('aria-expanded',String(!!items.length));position()}catch(e){if(e.name!=='AbortError'&&current===version)hide()}},120)}
 document.addEventListener('focusin',e=>{if(!e.target.matches(selector))return;hide();input=e.target;input.setAttribute('aria-autocomplete','list');input.setAttribute('aria-controls',box.id);input.setAttribute('autocomplete','off');suggest()});
 document.addEventListener('input',e=>{if(e.target===input&&!e.isComposing)suggest()});
 document.addEventListener('compositionend',e=>{if(e.target===input)suggest()});
 document.addEventListener('click',e=>{if(e.target===input)suggest()});
 document.addEventListener('focusout',e=>{if(e.target===input)hide()});
 document.addEventListener('pointerdown',e=>{if(e.target!==input&&!box.contains(e.target))hide()});
 document.addEventListener('keydown',e=>{if(e.target!==input||box.hidden||e.isComposing)return;if(e.key==='Escape'){e.preventDefault();hide()}else if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();selected=(selected+(e.key==='ArrowDown'?1:items.length-1)+items.length)%items.length;mark()}else if((e.key==='Enter'||e.key==='Tab')&&selected>=0){e.preventDefault();choose(selected)}});
 addEventListener('resize',hide);addEventListener('scroll',e=>{if(!box.contains(e.target))hide()},true);
})();
